import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(fileURLToPath(import.meta.url));
const modules = [
  "utilities.js",
  "state.js",
  "substitution_models.js",
  "distance_matrix.js",
  "upgma.js",
  "neighbour_joining.js",
  "simulation.js",
  "calibration.js",
  "newick.js",
  "tree_renderer.js",
  "charts.js",
  "app.js",
];

/** Convert one educational ES module into classic-script source. @param {string} source Module text. @returns {string} Source with local imports and export markers removed. The fixed dependency order supplies the same bindings inside one closure. */
function makeClassic(source) {
  return source
    .replace(/import[^;]+;\s*/g, "")
    .replace(/\bexport\s+(?=(?:const|let|var|class|function)\b)/g, "");
}

const parts = [];
for (const name of modules)
  parts.push(
    `\n/* js/${name} */\n${makeClassic(await readFile(join(root, "js", name), "utf8"))}`,
  );
await writeFile(
  join(root, "js", "explorer.bundle.js"),
  `/* Generated by html/build.mjs. Edit the source modules, then run: node html/build.mjs */\n(()=>{"use strict";${parts.join("")}\n})();\n`,
);
